name: "Create cluster using KinD"
on:
  pull_request:
    branches: [ master ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.17.0"
          verbosity: 3 # info = 0, debug = 3, trace = 2147483647
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy
        run: |
          # kind load docker-image --name=kind litmuschaos/ansible-runner:ci
          kubectl apply -f "./.github/kind-config/deploy.yaml"
